global using Dalamud.Game.ClientState.Conditions;
global using ECommons.DalamudServices;
global using ECommons.DalamudServices.Legacy;
global using ECommons.Logging;
global using Dalamud.Interface.Utility;
global using Dalamud.Bindings.ImGui;
global using System;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Linq;
global using System.Numerics;
global using System.Text;
global using System.Threading.Tasks;
global using static Weatherman.Static;
global using static Weatherman.Weatherman;