global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using ImGuiNET;
global using System.Numerics;
global using ECommons.Logging;
global using Dalamud.Game.ClientState.Conditions;
global using Dalamud.Interface.Internal.Notifications;
global using System.Diagnostics;
global using static Weatherman.Static;
global using ECommons.DalamudServices;